USE BoasPraticas
GO

/*
CREATE TABLE ESTOQUES (
	 CODIGO INT NOT NULL
	,
)
*/

CREATE TABLE LOJAS(
	 CODIGO			INT				NOT NULL
	,NOME			VARCHAR(50)		NOT NULL
	,IND_INATIVO	INT				NOT NULL DEFAULT 0
	CONSTRAINT PK_LOJA PRIMARY KEY(CODIGO)
);
GO