USE BoasPraticas
GO


CREATE TABLE ESTOQUES (
	 CODIGO_PRODUTO		INT			NOT NULL
	,CODIGO_FILIAL		INT			NOT NULL
	,QUANTIDADE			DECIMAL		NOT NULL DEFAULT 0
	CONSTRAINT  PK_ESTOQUES PRIMARY KEY(CODIGO_PRODUTO, CODIGO_FILIAL)
);
GO

-- Forcando Erro
INSERT INTO ESTOQUES(CODIGO_PRODUTO, CODIGO_FILIAL, QUANTIDADE) VALUES (2, 10, 1);
GO

-- Limpando o erro
DELETE FROM ESTOQUES;
GO

--Criando a Foreign Key para PRODUTOS
ALTER TABLE ESTOQUES
	ADD CONSTRAINT FK_ESTOQUES_LOJAS
	FOREIGN KEY (CODIGO_FILIAL)
	REFERENCES LOJAS(CODIGO);
GO

-- Criando a Foreign Key para LOJAS
ALTER TABLE ESTOQUES
	ADD CONSTRAINT FK_ESTOQUE_LOJAS
	FOREIGN KEY (CODIGO_CODIGO)
	REFERENCES LOJAS;
GO

-- Inserindo corretamente com as FOREIGN KEY adicionadas
INSERT INTO ESTOQUES(CODIGO_PRODUTO, CODIGO_FILIAL, QUANTIDADE) VALUES (2, 1000, 10);
GO

-- Selecionando os Produtos, Estoque das Lojas
SELECT   CODIGO_PRODUTO		AS 'Código'
		,PRODUTOS.CODIGO	AS 'Produto'
		,LOJAS.NOME			AS 'Filial'
		,QUANTIDADE			AS 'Quantidade'
  FROM   ESTOQUES
  INNER  JOIN LOJAS			ON CODIGO_FILIAL = LOJAS.CODIGO
  INNER  JOIN PRODUTOS		ON CODIGO_PRODUTO = PRODUTOS.CODIGO
  WHERE  PRODUTOS.IND_INATIVO = 0;
GO

--- Criando tabe LOJAS
CREATE TABLE LOJAS(
	 CODIGO			INT				NOT NULL
	,NOME			VARCHAR(50)		NOT NULL
	,IND_INATIVO	INT				NOT NULL DEFAULT 0
	CONSTRAINT PK_LOJA PRIMARY KEY(CODIGO)
);
GO

-- Inserindo itens a LOJAS
INSERT INTO LOJAS(CODIGO, NOME) VALUES (1000, 'Nova Iguaçu');
INSERT INTO LOJAS(CODIGO, NOME) VALUES (1001, 'São Paulo');
INSERT INTO LOJAS(CODIGO, NOME) VALUES (1002, 'Piracicaba');
GO